# treefmt.nix
{ pkgs, ... }:
{
  projectRootFile = "flake.nix";
  fail-on-change = true;
  # formatters = ["go" "toml" "haskell"]
  walk = "git"; # auto', 'git', 'jujutsu' or 'filesystem'

  # Enable the terraform formatter
  programs.terraform.enable = true;
  # Override the default package
  programs.terraform.package = pkgs.terraform_1;
  # Override the default settings generated by the above option
  settings.formatter.terraform.excludes = [ "hello.tf" ];
}