# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, ... }:

{
  imports = [
    # (modulesPath + "/installer/scan/not-detected.nix")
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "ata_piix"
      "vmw_pvscsi"
      "sd_mod"
      "sr_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ ];
    extraModulePackages = [ ];

    loader.grub = {
      # With an EF02 BIOS boot partition, disko adds the disk automatically.
      # devices = [ ];
      efiSupport = true;
      efiInstallAsRemovable = true;
    };
  };

  hardware = {
    # enableAllFirmware = true;
    # enableAllHardware = true;
    enableRedistributableFirmware = true;
  };
}
