# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{ pkgs, lib }:

let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
merge
  (merge
    (merge
      (merge
      {
        "christian-kohler"."npm-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
          name = "npm-intellisense";
          publisher = "christian-kohler";
          version = "1.4.5";
          sha256 = "1av0iwym6j5l2a522ikyjkrsyp4q3sws1d7y9brm3gdgghd8aawn";

        };
        "github"."remotehub" = vscode-utils.extensionFromVscodeMarketplace {
          name = "remotehub";
          publisher = "github";
          version = "0.64.0";
          sha256 = "1ii83py8665yp2iiw57fr9n5k7n0sx31s1rcybdx10axhp2hy7in";

        };
        "google"."geminicodeassist" = vscode-utils.extensionFromVscodeMarketplace {
          name = "geminicodeassist";
          publisher = "google";
          version = "2.30.1";
          sha256 = "0y90dy1xxqxif3s3k6di3yahjjqx12a91i9mgrilc1n5kvyh5z8m";

        };
        "googlecloudtools"."cloudcode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "cloudcode";
          publisher = "googlecloudtools";
          version = "2.28.0";
          sha256 = "088c2ajssbsn0fvjz3nwynmz4zvc8cdh6g5mfgdaw9lh6ynzq1ip";

        };
        "jbenden"."c-cpp-flylint" = vscode-utils.extensionFromVscodeMarketplace {
          name = "c-cpp-flylint";
          publisher = "jbenden";
          version = "1.15.0";
          sha256 = "1z1l9ygxsqjn8vpncjzyisdg2sirgzf4ghiv5ak32mkq3k8hgawk";

        };
        "jeff-hykin"."better-cpp-syntax" = vscode-utils.extensionFromVscodeMarketplace {
          name = "better-cpp-syntax";
          publisher = "jeff-hykin";
          version = "1.27.1";
          sha256 = "037nigza7n71j5vgl3qw0swrmy8gvfj9m8jbi1nb2a3lmsifivqq";

        };
        "jsynowiec"."vscode-insertdatestring" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-insertdatestring";
          publisher = "jsynowiec";
          version = "2.3.1";
          sha256 = "1cm29jggxax3d7i8s3jqs4z9ikh7n85blm8hrha0qz7r55wvc4ia";

        };
        "kevinrose"."vsc-python-indent" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vsc-python-indent";
          publisher = "kevinrose";
          version = "1.21.0";
          sha256 = "1zlkbxgl8bad8g1lm60z0zf5gr1011p696zps3azr89cdxa63wja";

        };
        "lpubsppop01"."vscode-auto-timestamp" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-auto-timestamp";
          publisher = "lpubsppop01";
          version = "0.0.8";
          sha256 = "0myzz3ssggvd95zhq5zpj46p9m270m7l1bnyx5abql1883y7sicf";

        };
        "mammothb"."gnuplot" = vscode-utils.extensionFromVscodeMarketplace {
          name = "gnuplot";
          publisher = "mammothb";
          version = "1.0.5";
          sha256 = "0pr0n0zrb4ccs565xxzvfms4a2mi73nr4i6m3pnb1myr5f2969zm";

        };
        "ms-python"."autopep8" = vscode-utils.extensionFromVscodeMarketplace {
          name = "autopep8";
          publisher = "ms-python";
          version = "2025.2.0";
          sha256 = "1xcs0gqpbm0hlzab11hl00qjjq3cama7gff99nkphy12fg7z4nip";

        };
        "ms-python"."mypy-type-checker" = vscode-utils.extensionFromVscodeMarketplace {
          name = "mypy-type-checker";
          publisher = "ms-python";
          version = "2025.2.0";
          sha256 = "125vr6irqn5q78ydgrql3lfkwjn264amzv52qkh8hv0w5r4dg7sl";

        };
        "ms-toolsai"."vscode-jupyter-powertoys" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-jupyter-powertoys";
          publisher = "ms-toolsai";
          version = "0.1.1";
          sha256 = "1bp05g1vbkbrhq8h9rrxg96g55ys09xdwidnv7hm43shp9dg8fz5";

        };
        "ms-vscode"."atom-keybindings" = vscode-utils.extensionFromVscodeMarketplace {
          name = "atom-keybindings";
          publisher = "ms-vscode";
          version = "3.3.0";
          sha256 = "12hkb2lm9c94b5y6zaxk6ajwx9q78c5jd46brm685qqm6py9ncxz";

        };
        "ms-vscode"."azure-repos" = vscode-utils.extensionFromVscodeMarketplace {
          name = "azure-repos";
          publisher = "ms-vscode";
          version = "0.40.0";
          sha256 = "1gzqb5wgsp79109y9qz06n24yfrw9cv9wizbyr6wwz4rdvnfj92s";

        };
        "ms-vscode"."cpptools-themes" = vscode-utils.extensionFromVscodeMarketplace {
          name = "cpptools-themes";
          publisher = "ms-vscode";
          version = "2.0.0";
          sha256 = "05r7hfphhlns2i7zdplzrad2224vdkgzb0dbxg40nwiyq193jq31";

        };
        "ms-vscode"."js-debug" = vscode-utils.extensionFromVscodeMarketplace {
          name = "js-debug";
          publisher = "ms-vscode";
          version = "1.97.1";
          sha256 = "15i4sc55cr09gzs5i0i27w9glhmil5l6y5rf64p70ismh1adhzcp";

        };
        "ms-vscode"."js-debug-companion" = vscode-utils.extensionFromVscodeMarketplace {
          name = "js-debug-companion";
          publisher = "ms-vscode";
          version = "1.1.3";
          sha256 = "14yyaan6ipa6klzjdg4f6npqqlyyjkx5v0xp5m5z2lklg28ai03k";

        };
        "ms-vscode"."remote-explorer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "remote-explorer";
          publisher = "ms-vscode";
          version = "0.4.3";
          sha256 = "12dwyl03gcsrn8fkr8vfixdkyfyyznbkvwblwzh74nf0978abggg";

        };
        "ms-vscode"."remote-repositories" = vscode-utils.extensionFromVscodeMarketplace {
          name = "remote-repositories";
          publisher = "ms-vscode";
          version = "0.42.0";
          sha256 = "1mz1ziygz290qz1g805ndrdr6z1pv47pzpln2fx378bcqc4y91ki";

        };
        "ms-vscode"."remote-server" = vscode-utils.extensionFromVscodeMarketplace {
          name = "remote-server";
          publisher = "ms-vscode";
          version = "1.5.2";
          sha256 = "0llrl0s9fll17sc1fxx5ndk5l9x25k4ln1gahpc7ljwhykyzg9hs";

        };
        "ms-vscode"."vscode-js-profile-table" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-js-profile-table";
          publisher = "ms-vscode";
          version = "1.0.10";
          sha256 = "024fqf2q6w4rnwh2hs88wymgjb3a6zbs5wni5s59vl4zvy6p8qbk";

        };
        "ms-vscode"."vscode-typescript-next" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-typescript-next";
          publisher = "ms-vscode";
          version = "5.9.20250330";
          sha256 = "199g2wak4c6c2gihlnrn5glgrv3xzabymvszm1hx7k02q3idmj2z";

        };
        "ombratteng"."nftables" = vscode-utils.extensionFromVscodeMarketplace {
          name = "nftables";
          publisher = "ombratteng";
          version = "0.7.0";
          sha256 = "0nnqxif5b7h6c2g8b72sjd2m4zi7s09gav2jr98dgyq0fc5ka6wz";

        };
        "seunlanlege"."action-buttons" = vscode-utils.extensionFromVscodeMarketplace {
          name = "action-buttons";
          publisher = "seunlanlege";
          version = "1.2.2";
          sha256 = "1skrnq8zsjqdbg1sclkynm3hgj9rgvsbzf5v966nw65r2y57hc7k";

        };
        "thfriedrich"."lammps" = vscode-utils.extensionFromVscodeMarketplace {
          name = "lammps";
          publisher = "thfriedrich";
          version = "1.8.12";
          sha256 = "0sji812rf89zb26jgws5lm0q81p0srxqm6av3m3hclhp42c24fsf";

        };
        "thmsrynr"."vscode-namegen" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-namegen";
          publisher = "thmsrynr";
          version = "0.2.1";
          sha256 = "1s1i7q400rg6kgzkj20bb0rk93nmph67ysdsjiv2q6aijlq93gd4";

        };
        "trond-snekvik"."simple-rst" = vscode-utils.extensionFromVscodeMarketplace {
          name = "simple-rst";
          publisher = "trond-snekvik";
          version = "1.5.4";
          sha256 = "1js1489nd9fycvpgh39mwzpbqm28qi4gzi68443v3vhw3dsg4wjv";

        };
        "trunk"."io" = vscode-utils.extensionFromVscodeMarketplace {
          name = "io";
          publisher = "trunk";
          version = "3.19.0";
          sha256 = "1acqvdg642q936w0mpljci496xbjk754qjl9q83rqmi7w5d9fyb9";

        };
        "turaiiao"."vscode-author-header" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-author-header";
          publisher = "turaiiao";
          version = "1.0.4";
          sha256 = "14az8qnbj1jalfk1r1w7cb7s5qy2w9l0dpsd7ws6zp1cf7zy4m1l";

        };
        "william-voyek"."vscode-nginx" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-nginx";
          publisher = "william-voyek";
          version = "0.7.2";
          sha256 = "0s4akrhdmrf8qwn6vp8kc31k5hx2k2wml5mcashfc09hxiqsf2cq";

        };
        "ymotongpoo"."licenser" = vscode-utils.extensionFromVscodeMarketplace {
          name = "licenser";
          publisher = "ymotongpoo";
          version = "1.10.0";
          sha256 = "03q38fnqhppairlsm9plvxqsqm1jid6j6dkjvk68w50c8jf8kyrw";

        };
        "zhikui"."vscode-openfoam" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-openfoam";
          publisher = "zhikui";
          version = "0.0.6";
          sha256 = "0g73xlr0j1cg58m2s1la2m3l1msf5dpkh5fpx3ms0wi5ympgkhmy";

        };
      }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) {
          "ms-python"."vscode-python-envs" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-python-envs";
            publisher = "ms-python";
            version = "0.1.2024121005";
            sha256 = "0bjwnr2wnqqcgd2k8i3h83vrxp49f1ik05aj41vwq2xh9s4ygh6x";
            arch = "linux-x64";

          };
        }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) {
        "ms-python"."vscode-python-envs" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-python-envs";
          publisher = "ms-python";
          version = "0.1.2024121005";
          sha256 = "1nd2i08mr8blfl9bsvm582a06awq1r146rrq7xhpvw70givcs9k4";
          arch = "linux-arm64";

        };
      }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) {
      "ms-python"."vscode-python-envs" = vscode-utils.extensionFromVscodeMarketplace {
        name = "vscode-python-envs";
        publisher = "ms-python";
        version = "0.1.2024121005";
        sha256 = "0zggyy9nly83fszahqgw54d40gl8pn19yfdgb22mnlgwz707xb9v";
        arch = "darwin-x64";

      };
    }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) {
    "ms-python"."vscode-python-envs" = vscode-utils.extensionFromVscodeMarketplace {
      name = "vscode-python-envs";
      publisher = "ms-python";
      version = "0.1.2024121005";
      sha256 = "0ak1sfm2z51cmhp0z0ni8qpzh90ncn1ar8rsid3sqmf3j6rh2x45";
      arch = "darwin-arm64";

    };
  })

