# Generated by firefox-policies2nix.py. Do not edit.
# policies-schema.json source: https://raw.githubusercontent.com/mozilla/enterprise-firefox/9afafe8f95823cc25bad963314a1e2a53cc30f65/browser/components/enterprisepolicies/schemas/policies-schema.json
# enterprise-admin-reference source: https://github.com/mozilla/enterprise-admin-reference/tree/9334650499afec16eae178433bcfe239faef1a55/src/content/docs/reference/policies
{
  deprecated = [ "DisablePocket" ];
  preferences-affected = {
    "browser.ml.chat.enabled" = [
      "AIChatbot"
      "AIControls"
      "GenerativeAI"
    ];
    "browser.ml.chat.provider" = [ "AIChatbot" ];
    "browser.ml.chat.providers" = [ "AIChatbot" ];
    "browser.ml.chat.shortcuts" = [ "AIChatbot" ];
    "browser.ml.chat.prompts.0" = [ "AIChatbot" ];
    "browser.ml.chat.prompts.1" = [ "AIChatbot" ];
    "browser.ml.chat.prompts.2" = [ "AIChatbot" ];
    "browser.ml.chat.prompts.3" = [ "AIChatbot" ];
    "browser.ml.chat.page" = [
      "AIControls"
      "GenerativeAI"
    ];
    "browser.ai.control.sidebarChatbot" = [ "AIControls" ];
    "browser.translations.enable" = [
      "AIControls"
      "TranslateEnabled"
    ];
    "browser.ai.control.translations" = [ "AIControls" ];
    "pdfjs.enableAltText" = [ "AIControls" ];
    "browser.ai.control.pdfjsAltText" = [ "AIControls" ];
    "browser.ml.linkPreview.enabled" = [ "AIControls" ];
    "browser.ai.control.linkPreviewKeyPoints" = [ "AIControls" ];
    "browser.tabs.groups.smart.userEnabled" = [
      "AIControls"
      "GenerativeAI"
    ];
    "browser.ai.control.smartTabGroups" = [ "AIControls" ];
    "browser.ai.control.smartWindow" = [ "AIControls" ];
    "widget.disable_file_pickers" = [ "AllowFileSelectionDialogs" ];
    "app.update.auto" = [ "AppAutoUpdate" ];
    "app.update.url" = [ "AppUpdateURL" ];
    "network.negotiate-auth.trusted-uris" = [ "Authentication" ];
    "network.negotiate-auth.delegation-uris" = [ "Authentication" ];
    "network.automatic-ntlm-auth.trusted-uris" = [ "Authentication" ];
    "network.automatic-ntlm-auth.allow-non-fqdn" = [ "Authentication" ];
    "network.negotiate-auth.allow-non-fqdn" = [ "Authentication" ];
    "network.automatic-ntlm-auth.allow-proxies" = [ "Authentication" ];
    "network.negotiate-auth.allow-proxies" = [ "Authentication" ];
    "network.auth.private-browsing-sso" = [ "Authentication" ];
    "extensions.formautofill.addresses.enabled" = [ "AutofillAddressEnabled" ];
    "extensions.formautofill.creditCards.enabled" = [ "AutofillCreditCardEnabled" ];
    "app.update.background.enabled" = [ "BackgroundAppUpdate" ];
    "network.captive-portal-service.enabled" = [ "CaptivePortal" ];
    "security.enterprise_roots.enabled" = [ "Certificates" ];
    "security.tls.enable_mlkem1024" = [ "CNSA2KeyAgreementEnabled" ];
    "browser.contentanalysis.agent_name" = [ "ContentAnalysis" ];
    "browser.contentanalysis.agent_timeout" = [ "ContentAnalysis" ];
    "browser.contentanalysis.allow_url_regex_list" = [ "ContentAnalysis" ];
    "browser.contentanalysis.bypass_for_same_tab_operations" = [ "ContentAnalysis" ];
    "browser.contentanalysis.client_signature" = [ "ContentAnalysis" ];
    "browser.contentanalysis.default_result" = [ "ContentAnalysis" ];
    "browser.contentanalysis.deny_url_regex_list" = [ "ContentAnalysis" ];
    "browser.contentanalysis.enabled" = [ "ContentAnalysis" ];
    "browser.contentanalysis.interception_point.clipboard.enabled" = [ "ContentAnalysis" ];
    "browser.contentanalysis.interception_point.clipboard.plain_text_only" = [ "ContentAnalysis" ];
    "browser.contentanalysis.interception_point.download.enabled" = [ "ContentAnalysis" ];
    "browser.contentanalysis.interception_point.drag_and_drop.enabled" = [ "ContentAnalysis" ];
    "browser.contentanalysis.interception_point.drag_and_drop.plain_text_only" = [ "ContentAnalysis" ];
    "browser.contentanalysis.interception_point.file_upload.enabled" = [ "ContentAnalysis" ];
    "browser.contentanalysis.interception_point.print.enabled" = [ "ContentAnalysis" ];
    "browser.contentanalysis.is_per_user" = [ "ContentAnalysis" ];
    "browser.contentanalysis.max_connections" = [ "ContentAnalysis" ];
    "browser.contentanalysis.pipe_path_name" = [ "ContentAnalysis" ];
    "browser.contentanalysis.show_blocked_result" = [ "ContentAnalysis" ];
    "browser.contentanalysis.timeout_result" = [ "ContentAnalysis" ];
    "network.cookie.cookieBehavior" = [ "Cookies" ];
    "network.cookie.cookieBehavior.pbmode" = [ "Cookies" ];
    "network.cookie.lifetimePolicy" = [ "Cookies" ];
    "browser.crashReports.unsubmittedCheck.enabled" = [ "CrashReportsSubmit" ];
    "browser.crashReports.unsubmittedCheck.autoSubmit2" = [ "CrashReportsSubmit" ];
    "browser.tabs.crashReporting.includeURL" = [ "CrashReportsSubmit" ];
    "browser.tabs.crashReporting.sendReport" = [ "CrashReportsSubmit" ];
    "browser.shell.checkDefaultBrowser" = [
      "DefaultBrowserSettingEnabled"
      "DontCheckDefaultBrowser"
    ];
    "browser.download.dir" = [
      "DefaultDownloadDirectory"
      "DownloadDirectory"
    ];
    "browser.download.folderList" = [
      "DefaultDownloadDirectory"
      "DownloadDirectory"
    ];
    "dom.webserial.enabled" = [ "DefaultSerialGuardSetting" ];
    "security.ssl3.ecdhe_rsa_aes_128_gcm_sha256" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_ecdsa_aes_128_gcm_sha256" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_ecdsa_chacha20_poly1305_sha256" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_ecdsa_aes_256_gcm_sha384" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_rsa_aes_256_gcm_sha384" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_rsa_aes_128_sha" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_ecdsa_aes_128_sha" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_rsa_aes_256_sha" = [ "DisabledCiphers" ];
    "security.ssl3.ecdhe_ecdsa_aes_256_sha" = [ "DisabledCiphers" ];
    "security.ssl3.dhe_rsa_aes_128_sha" = [ "DisabledCiphers" ];
    "security.ssl3.dhe_rsa_aes_256_sha" = [ "DisabledCiphers" ];
    "security.ssl3.rsa_aes_128_gcm_sha256" = [ "DisabledCiphers" ];
    "security.ssl3.rsa_aes_256_gcm_sha384" = [ "DisabledCiphers" ];
    "security.ssl3.rsa_aes_128_sha" = [ "DisabledCiphers" ];
    "security.ssl3.rsa_aes_256_sha" = [ "DisabledCiphers" ];
    "security.ssl3.deprecated.rsa_des_ede3_sha" = [ "DisabledCiphers" ];
    "security.tls13.chacha20_poly1305_sha256" = [ "DisabledCiphers" ];
    "security.tls13.aes_128_gcm_sha256" = [ "DisabledCiphers" ];
    "security.tls13.aes_256_gcm_sha384" = [ "DisabledCiphers" ];
    "devtools.policy.disabled" = [ "DisableDeveloperTools" ];
    "network.dns.echconfig.enabled" = [ "DisableEncryptedClientHello" ];
    "network.dns.http3_echconfig.enabled" = [ "DisableEncryptedClientHello" ];
    "identity.fxaccounts.enabled" = [ "DisableFirefoxAccounts" ];
    "extensions.screenshots.disabled" = [ "DisableFirefoxScreenshots" ];
    "browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons" = [
      "DisableFirefoxStudies"
      "InstallAddonsPermission"
      "UserMessaging"
    ];
    "browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features" = [
      "DisableFirefoxStudies"
      "InstallAddonsPermission"
      "UserMessaging"
    ];
    "browser.formfill.enable" = [ "DisableFormHistory" ];
    "extensions.pocket.enabled" = [ "DisablePocket" ];
    "browser.disableResetPrompt" = [ "DisableProfileRefresh" ];
    "security.certerror.hideAddException" = [ "DisableSecurityBypass" ];
    "browser.safebrowsing.allowOverride" = [ "DisableSecurityBypass" ];
    "datareporting.healthreport.uploadEnabled" = [ "DisableTelemetry" ];
    "datareporting.policy.dataSubmissionEnabled" = [ "DisableTelemetry" ];
    "toolkit.telemetry.archive.enabled" = [ "DisableTelemetry" ];
    "datareporting.usage.uploadEnabled" = [ "DisableTelemetry" ];
    "network.trr.mode" = [ "DNSOverHTTPS" ];
    "network.trr.uri" = [ "DNSOverHTTPS" ];
    "network.trr.excluded-domains" = [ "DNSOverHTTPS" ];
    "browser.download.useDownloadDir" = [
      "DownloadDirectory"
      "PromptForDownloadLocation"
    ];
    "privacy.trackingprotection.enabled" = [ "EnableTrackingProtection" ];
    "privacy.trackingprotection.pbmode.enabled" = [ "EnableTrackingProtection" ];
    "privacy.trackingprotection.cryptomining.enabled" = [ "EnableTrackingProtection" ];
    "privacy.trackingprotection.fingerprinting.enabled" = [ "EnableTrackingProtection" ];
    "privacy.fingerprintingProtection" = [ "EnableTrackingProtection" ];
    "privacy.trackingprotection.emailtracking.enabled" = [ "EnableTrackingProtection" ];
    "privacy.trackingprotection.emailtracking.pbmode.enabled" = [ "EnableTrackingProtection" ];
    "privacy.trackingprotection.allow_list.baseline.enabled" = [ "EnableTrackingProtection" ];
    "privacy.trackingprotection.allow_list.convenience.enabled" = [ "EnableTrackingProtection" ];
    "media.eme.enabled" = [ "EncryptedMediaExtensions" ];
    "extensions.update.enabled" = [ "ExtensionUpdate" ];
    "browser.newtabpage.activity-stream.showSearch" = [ "FirefoxHome" ];
    "browser.newtabpage.activity-stream.feeds.topsites" = [ "FirefoxHome" ];
    "browser.newtabpage.activity-stream.feeds.section.highlights" = [ "FirefoxHome" ];
    "browser.newtabpage.activity-stream.feeds.section.topstories" = [ "FirefoxHome" ];
    "browser.newtabpage.activity-stream.feeds.snippets" = [ "FirefoxHome" ];
    "browser.newtabpage.activity-stream.showSponsoredTopSites" = [ "FirefoxHome" ];
    "browser.newtabpage.activity-stream.showSponsored" = [ "FirefoxHome" ];
    "browser.newtabpage.activity-stream.showWeather" = [ "FirefoxHome" ];
    "browser.urlbar.suggest.quicksuggest.all" = [ "FirefoxSuggest" ];
    "browser.urlbar.suggest.quicksuggest.sponsored" = [ "FirefoxSuggest" ];
    "browser.urlbar.quicksuggest.dataCollection.enabled" = [ "FirefoxSuggest" ];
    "browser.ml.linkPreview.optin" = [ "GenerativeAI" ];
    "browser.fixup.dns_first_for_single_words" = [ "GoToIntranetSiteForSingleWordEntryInAddressBar" ];
    "layers.acceleration.disabled" = [ "HardwareAcceleration" ];
    "browser.startup.homepage" = [ "Homepage" ];
    "browser.startup.page" = [ "Homepage" ];
    "browser.sessionstore.newTabOnRestore" = [ "Homepage" ];
    "browser.sessionstore.newTabOnRestore.showSetting" = [ "Homepage" ];
    "dom.security.https_only_mode" = [ "HttpsOnlyMode" ];
    "xpinstall.enabled" = [ "InstallAddonsPermission" ];
    "browser.ipProtection.enabled" = [ "IPProtectionAvailable" ];
    "network.cookie.sameSite.laxByDefault" = [ "LegacySameSiteCookieBehaviorEnabled" ];
    "network.cookie.sameSite.laxByDefault.disabledHosts" = [
      "LegacySameSiteCookieBehaviorEnabledForDomainList"
    ];
    "capability.policy.policynames" = [ "LocalFileLinks" ];
    "capability.policy.localfilelinks_*" = [ "LocalFileLinks" ];
    "network.lna.enabled" = [ "LocalNetworkAccess" ];
    "network.lna.block_trackers" = [ "LocalNetworkAccess" ];
    "network.lna.blocking" = [ "LocalNetworkAccess" ];
    "network.lna.skip-domains" = [ "LocalNetworkAccess" ];
    "network.http.microsoft-entra-sso.enabled" = [ "MicrosoftEntraSSO" ];
    "network.dns.disablePrefetch" = [ "NetworkPrediction" ];
    "network.dns.disablePrefetchFromHTTPS" = [ "NetworkPrediction" ];
    "browser.newtabpage.enabled" = [ "NewTabPage" ];
    "signon.rememberSignons" = [
      "OfferToSaveLogins"
      "OfferToSaveLoginsDefault"
      "PasswordManagerEnabled"
    ];
    "startup.homepage_welcome_url" = [ "OverrideFirstRunPage" ];
    "browser.aboutwelcome.enabled" = [
      "OverrideFirstRunPage"
      "UserMessaging"
    ];
    "startup.homepage_override_url" = [ "OverridePostUpdatePage" ];
    "pref.privacy.disable_button.view_passwords" = [ "PasswordManagerEnabled" ];
    "browser.contextual-password-manager.enabled" = [ "PasswordManagerEnabled" ];
    "pdfjs.disabled" = [ "PDFjs" ];
    "pdfjs.enablePermissions" = [ "PDFjs" ];
    "permissions.default.camera" = [ "Permissions" ];
    "permissions.default.microphone" = [ "Permissions" ];
    "permissions.default.geo" = [ "Permissions" ];
    "permissions.default.desktop-notification" = [ "Permissions" ];
    "media.autoplay.default" = [ "Permissions" ];
    "permissions.default.xr" = [ "Permissions" ];
    "permissions.default.screen" = [ "Permissions" ];
    "media.videocontrols.picture-in-picture.video-toggle.enabled" = [ "PictureInPicture" ];
    "dom.disable_open_during_load" = [ "PopupBlocking" ];
    "security.tls.enable_kyber" = [ "PostQuantumKeyAgreementEnabled" ];
    "network.http.http3.enable_kyber" = [ "PostQuantumKeyAgreementEnabled" ];
    "media.webrtc.enable_pq_hybrid_kex" = [ "PostQuantumKeyAgreementEnabled" ];
    "print.enabled" = [ "PrintingEnabled" ];
    "network.proxy.type" = [ "Proxy" ];
    "network.proxy.autoconfig_url" = [ "Proxy" ];
    "network.proxy.socks_remote_dns" = [ "Proxy" ];
    "signon.autologin.proxy" = [ "Proxy" ];
    "network.proxy.socks_version" = [ "Proxy" ];
    "network.proxy.no_proxies_on" = [ "Proxy" ];
    "network.proxy.share_proxy_settings" = [ "Proxy" ];
    "network.proxy.http" = [ "Proxy" ];
    "network.proxy.http_port" = [ "Proxy" ];
    "network.proxy.ftp" = [ "Proxy" ];
    "network.proxy.ftp_port" = [ "Proxy" ];
    "network.proxy.ssl" = [ "Proxy" ];
    "network.proxy.ssl_port" = [ "Proxy" ];
    "network.proxy.socks" = [ "Proxy" ];
    "network.proxy.socks_port" = [ "Proxy" ];
    "privacy.sanitize.sanitizeOnShutdown" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown.cache" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown.cookies" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown.downloads" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown.formdata" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown.history" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown.sessions" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown.siteSettings" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown.offlineApps" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown_v2.browsingHistoryAndDownloads" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown_v2.cookiesAndStorage" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown_v2.cache" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown_v2.siteSettings" = [ "SanitizeOnShutdown" ];
    "privacy.clearOnShutdown_v2.formdata" = [ "SanitizeOnShutdown" ];
    "browser.urlbar.suggest.searches" = [ "SearchSuggestEnabled" ];
    "browser.search.suggest.enabled" = [ "SearchSuggestEnabled" ];
    "security.tls.version.max" = [ "SSLVersionMax" ];
    "security.tls.version.min" = [ "SSLVersionMin" ];
    "browser.download.start_downloads_in_tmp_dir" = [ "StartDownloadsInTempDirectory" ];
    "browser.preferences.moreFromMozilla" = [ "UserMessaging" ];
    "browser.preferences.experimental" = [ "UserMessaging" ];
    "print.prefer_system_dialog" = [ "UseSystemPrintDialog" ];
    "browser.search.visualSearch.featureGate" = [ "VisualSearchEnabled" ];
    "network.http.windows-sso.enabled" = [ "WindowsSSO" ];
    "dom.xslt.enabled" = [ "XSLTEnabled" ];
  };
}
